setup(name='functionals',
      version='0.1',
      description='Functions for functional programming.',
      url='http://www.github.com/philosofool/functionals',
      author='S. J. Lenhart',
      author_email='your.name@example.com',
      license='MIT',
      packages=['functionals'],
      zip_safe=False)